/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import console.ConsoleUtility;
import db.DBHandler;
import db.Kontak;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Aurelia
 */
public class TambahKontak extends javax.swing.JFrame
{

    private DBHandler db;
    private final ConsoleUtility cu = new ConsoleUtility(true, true);

    public TambahKontak(DBHandler db)
    {
        this.db = db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TambahNamaTXT = new javax.swing.JTextField();
        TambahHPTXT = new javax.swing.JTextField();
        TambahKategoriTXT = new javax.swing.JTextField();
        TambahKontakButton = new javax.swing.JButton();
        BatalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tambahkan Kontak");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(253, 152, 96));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/AddContact.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/TambahKontak2.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(253, 152, 96));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Nama");

        jLabel4.setText("No HP");

        jLabel5.setText("Kategori");

        TambahNamaTXT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TambahNamaTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TambahKategoriTXT)
                    .addComponent(TambahHPTXT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TambahNamaTXT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TambahNamaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TambahHPTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TambahKategoriTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TambahKontakButton.setText("Tambahkan Kontak");
        TambahKontakButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TambahKontakButtonActionPerformed(evt);
            }
        });

        BatalButton.setText("Batal");
        BatalButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BatalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TambahKontakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BatalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TambahKontakButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(BatalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TambahKontakButton.getAccessibleContext().setAccessibleName("AddKontakBtn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahNamaTXTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TambahNamaTXTActionPerformed
    {//GEN-HEADEREND:event_TambahNamaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahNamaTXTActionPerformed

    private void TambahKontakButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TambahKontakButtonActionPerformed
    {//GEN-HEADEREND:event_TambahKontakButtonActionPerformed
        String nama = this.cu.titleCase(TambahNamaTXT.getText());
        String hp = this.cu.titleCase(TambahHPTXT.getText());
        String kategori = this.cu.titleCase(TambahKategoriTXT.getText());

        if (nama.length() > 45)
        {
            JOptionPane.showMessageDialog(this,
                    "Nama Tidak Bisa Lebih dari 45 Karakter!",
                    "Field Error",
                    JOptionPane.ERROR_MESSAGE);
            TambahNamaTXT.setBackground(Color.red);
        }
        else if (nama.equals(""))
        {
            JOptionPane.showMessageDialog(this,
                    "Nama Tidak Bisa Kosong !",
                    "Field Error",
                    JOptionPane.ERROR_MESSAGE);
            TambahNamaTXT.setBackground(Color.red);
        }
        else if (hp.length() > 12)
        {
            JOptionPane.showMessageDialog(this,
                    "No Handphone Tidak Bisa Lebih Dari 12 Karakter !",
                    "Field Error",
                    JOptionPane.ERROR_MESSAGE);
            TambahHPTXT.setBackground(Color.red);
        }
        else if (hp.equals(""))
        {
            JOptionPane.showMessageDialog(this,
                    "No Handphone Tidak Bisa Kosong !",
                    "Field Error",
                    JOptionPane.ERROR_MESSAGE);
            TambahHPTXT.setBackground(Color.red);
        }
        else if (kategori.length() > 25)
        {
            JOptionPane.showMessageDialog(this,
                    "Kategori Tidak Bisa Lebih Dari 25 Karakter !",
                    "Field Error",
                    JOptionPane.ERROR_MESSAGE);
            TambahKategoriTXT.setBackground(Color.red);
        }
        else if (kategori.equals(""))
        {
            JOptionPane.showMessageDialog(this,
                    "Kategori Tidak Bisa Kosong",
                    "Field Error",
                    JOptionPane.ERROR_MESSAGE);
            TambahKategoriTXT.setBackground(Color.red);
        }
        else
        {
            TambahNamaTXT.setBackground(Color.white);
            TambahHPTXT.setBackground(Color.white);
            TambahKategoriTXT.setBackground(Color.white);

            TambahNamaTXT.setText(nama);
            TambahHPTXT.setText(hp);
            TambahKategoriTXT.setText(kategori);

            if (this.db.addKontak(new Kontak(nama, hp, kategori)) == true)
            {
                JOptionPane.showMessageDialog(this,
                        "Data Berhasil Ditambahkan");
            }
            else
            {
                JOptionPane.showMessageDialog(this,
                        "Data tidak bisa ditambahkan !",
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
            }

            super.dispose();
        }
    }//GEN-LAST:event_TambahKontakButtonActionPerformed

    private void BatalButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BatalButtonActionPerformed
    {//GEN-HEADEREND:event_BatalButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_BatalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TambahKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TambahKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TambahKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TambahKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new TambahKontak().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalButton;
    private javax.swing.JTextField TambahHPTXT;
    private javax.swing.JTextField TambahKategoriTXT;
    private javax.swing.JButton TambahKontakButton;
    private javax.swing.JTextField TambahNamaTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
